### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-introspector#13]
What needs to be done

- [ ] Implement basic functionality tests to achieve some basic/sane level of coverage. 
- [x] Fix test flakyness. Tests are using external nodes for RPC calls via subxt that can be unreachable. We should spawn a dev node using a docker image.

**Comment by AndreiEres** [comment]
What needs to be done

- [ ] Implement basic functionality tests to achieve some basic/sane level of coverage. https://github.com/paritytech/polkadot-introspector/issues/60
- [ ] Fix test flakyness. Tests are using external nodes for RPC calls via subxt that can be unreachable. We should spawn a dev node using a docker image. https://github.com/paritytech/polkadot-introspector/issues/84

**Comment by AndreiEres** [comment]
@sandreim, about the test flakiness. 

In tests we use external nodes for RPC calls that can be unreachable. To solve it we could spawn a dev node using a docker image. 

After a few experiments with the CI team, we found that a dev node needs a couple of minutes to be ready, even with warp sync. Considering that our RPC tests are mostly smoke-like, I'd rather restart failed tests than set up a slow pipeline.

What do you think?

**Comment by sandreim** [comment]
We could spin up a small zombienet network to test this, just 1 validator and 1 parachain should do it.

**Comment by AndreiEres** [comment]
Since https://github.com/paritytech/polkadot-introspector/pull/445 we spawn a zombienet in the test stage instead of querying the real chain.
